### ISSUE TITLE
Config handling for out of date config files.

### ISSUE THREAD

**Issue by mdamonconnolly** [JI511/Personal_Fitness#62]
## Description

Config file currently has a problem where it cannot handle the errors thrown by configparser when trying to pull data that doesn't exist because the .cfg file is out of date.

## Reproduce
* Run program so the program creates the log file.
* Alter utilities.py and add in a new "path" to constants.py
```python
testPath = ""
```
* Add it to the `DATA` entry in the `initCfg()` and make the necessary changes in `readCfg()` matching the other constants paths.
* Run program again to see error.

## Brief
InitCfg() does _not_ get called because the config file does exist so instead, only readCfg() gets called. 
readCfg() tries to read the new values and then throw an error because the values don't exist. 

There needs to be a way to handle the error and give the missing entry a default value, effectively updating the config file.

**Comment by mdamonconnolly** [comment]
Note: I have thought about using a "Defaults" value set to use both when creating a new .cfg file and also when filling in missing values, but I didn't want to clutter `Utilities.py` with this. The other option which i think is far less graceful, would be `if` statements for every entry on the `cfgRead()`.

**Comment by JI511** [comment]
An option would be to loop through every option in the default constant list when trying to read the config, and add the value if the key doesnt exist. I see how this could be an issue while in development and adding something with an old config file.

**Comment by JI511** [comment]
Completed
